/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.exceptions;

import java.io.Serializable;

/**
 *
 **/
public class ImplementationException extends JFBException implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6732563012335118918L;

}