/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.exceptions;

import java.io.Serializable;

/**
 *
 **/
public class JFBImplementationException extends JFBException implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -6732563012335118918L;

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Throwable#getMessage()
	 */
	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return "Incorrect implementation which violates supporting interface structure";
	}

}