/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.exceptions;

import java.io.Serializable;

/**
 *
 **/
public class ObjectiveImplementationException extends JFBImplementationException implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 605257540643037132L;

	@Override
	public String getMessage() {
		return super.getMessage() + ", possibly adding an objective which does not implement a specific interface";
	}

}