/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.exceptions;

import java.io.Serializable;

/**
 *
 **/
public class AbilityImplementationException extends ImplementationException implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7392165759485312000L;

}