/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.exceptions;

import java.io.Serializable;

/**
 *
 **/
public class ObjectiveImplementationException extends ImplementationException implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 605257540643037132L;

}