/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.objectives;

/**
 *
 **/
public abstract class JFBAbstractGameObjective extends JFBAbstractObjective implements JFBGameObjectiveInterface {

}