/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.objectives;

/**
 *
 **/
public class SimpleGameObjective extends JFBAbstractGameObjective implements JFBGameObjectiveInterface {

}