/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.abilities;

import java.util.HashSet;

import com.jfbuilds.playngame.general.JFBActionInterface;
import com.jfbuilds.playngame.general.JFBConditionInterface;
import com.jfbuilds.playngame.general.JFBContainerInterface;
import com.jfbuilds.playngame.general.JFBDisplayInterface;
import com.jfbuilds.playngame.general.JFBEventBindsInterface;
import com.jfbuilds.playngame.general.JFBResetInterface;

/**
 *
 **/
public interface JFBAbilityInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    boolean activated = false;
//
//    int value = 0;
//
//    JFBEventBindsInterface eventBinds = null;
//
//    JFBConditionInterface condition = null;
//
//    JFBActionInterface action = null;
//
//    JFBDisplayInterface display = null;
//
//    JFBResetInterface reset = null;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public boolean isActivated() ;

    /**
     *
     **/
    public void setActivated(boolean activated_) ;

    /**
     *
     **/
    public int getValue() ;

    /**
     *
     **/
    public void setValue(int value_) ;

    /**
     *
     **/
    public JFBConditionInterface getCondition() ;

    /**
     *
     **/
    public void setCondition(JFBConditionInterface condition_) ;

    /**
     *
     **/
    public JFBActionInterface getAction() ;

    /**
     *
     **/
    public void setAction(JFBActionInterface action_) ;

    /**
     *
     **/
    public JFBDisplayInterface getDisplay() ;

    /**
     *
     **/
    public void setDisplay(JFBDisplayInterface display_) ;

    /**
     *
     **/
    public JFBResetInterface getReset() ;

    /**
     *
     **/
    public void setReset(JFBResetInterface reset_) ;

    /**
     *
     **/
    public JFBEventBindsInterface getEventBinds() ;

    /**
     *
     **/
    public void setEventBinds(JFBEventBindsInterface eventBinds_) ;

    /**
     *
     **/
    public boolean isAbilityCandidate(JFBAbilityInterface candidate) ;
    
    /**
    *
    **/
   public HashSet<? extends JFBAbilityInterface> getAbilityFamily() ;

   /**
   *
   **/
  public void setAbilityFamily(HashSet<? extends JFBAbilityInterface> abilityFamily_) ;
  
  /**
  *
  **/
 public void setParent(JFBContainerInterface parent_) ;
 
 /**
 *
 **/
 public JFBContainerInterface parent() ;
    

}