/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.abilities;

/**
 *
 **/
public abstract class JFBAbstractFragmentAbility extends JFBAbstractAbility implements JFBFragmentAbilityInterface {
}