/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.abilities;

/**
 *
 **/
public abstract class JFBAbstractSceneAbility extends JFBAbstractAbility implements JFBSceneAbilityInterface {

}