/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.abilities;

/**
 *
 **/
public abstract class JFBAbstractGameAbility extends JFBAbstractAbility implements JFBGameAbilityInterface {

}