/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.abilities;

import java.util.HashSet;

import com.jfbuilds.playngame.general.JFBActionInterface;
import com.jfbuilds.playngame.general.JFBConditionInterface;
import com.jfbuilds.playngame.general.JFBContainerInterface;
import com.jfbuilds.playngame.general.JFBDisplayInterface;
import com.jfbuilds.playngame.general.JFBEventBindsInterface;
import com.jfbuilds.playngame.general.JFBResetInterface;

/**
 *
 **/
public interface JFBAbilityInterface {

	/* ===================================== */
	/* == Member Variables == */
	/* ===================================== */

	// boolean activated = false;
	//
	// int value = 0;
	//
	// JFBEventBindsInterface eventBinds = null;
	//
	// JFBConditionInterface condition = null;
	//
	// JFBActionInterface action = null;
	//
	// JFBDisplayInterface display = null;
	//
	// JFBResetInterface reset = null;

	/* ===================================== */
	/* == Methods == */
	/* ===================================== */

	/**
	 *
	 **/
	public HashSet<? extends JFBAbilityInterface> getAbilityFamily();

	/**
	 *
	 **/
	public JFBActionInterface getAction();

	/**
	 *
	 **/
	public JFBConditionInterface getCondition();

	/**
	 *
	 **/
	public JFBDisplayInterface getDisplay();

	/**
	 *
	 **/
	public JFBEventBindsInterface getEventBinds();

	/**
	 *
	 **/
	public JFBResetInterface getReset();

	/**
	 *
	 **/
	public int getValue();

	/**
	 *
	 **/
	public boolean isAbilityCandidate(JFBAbilityInterface candidate);

	/**
	 *
	 **/
	public boolean isActivated();

	/**
	 *
	 **/
	public JFBContainerInterface parent();

	/**
	 *
	 **/
	public void setAbilityFamily(HashSet<? extends JFBAbilityInterface> abilityFamily_);

	/**
	 *
	 **/
	public void setAction(JFBActionInterface action_);

	/**
	 *
	 **/
	public void setActivated(boolean activated_);

	/**
	 *
	 **/
	public void setCondition(JFBConditionInterface condition_);

	/**
	 *
	 **/
	public void setDisplay(JFBDisplayInterface display_);

	/**
	 *
	 **/
	public void setEventBinds(JFBEventBindsInterface eventBinds_);

	/**
	 *
	 **/
	public void setParent(JFBContainerInterface parent_);

	/**
	 *
	 **/
	public void setReset(JFBResetInterface reset_);

	/**
	 *
	 **/
	public void setValue(int value_);

}