/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.objectives;

/**
 *
 **/
public abstract class JFBAbstractFragmentObjective extends JFBAbstractObjective implements JFBFragmentObjectiveInterface {

}