/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.objectives;

/**
 *
 **/
public abstract class JFBAbstractSceneObjective extends JFBAbstractObjective implements JFBSceneObjectiveInterface {

}