/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.objectives;

import java.util.HashSet;

import com.jfbuilds.playngame.general.JFBActionInterface;
import com.jfbuilds.playngame.general.JFBConditionInterface;
import com.jfbuilds.playngame.general.JFBContainerInterface;
import com.jfbuilds.playngame.general.JFBEventBindsInterface;
import com.jfbuilds.playngame.general.JFBResetInterface;
import com.jfbuilds.playngame.general.JFBStatusInterface;

/**
 *
 **/
public interface JFBObjectiveInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    private boolean activated;
//
//    private int value;
//
//    private int steps;
//
//    private int incrementalValue;
//
//    private JFBConditionInterface condition;
//
//    private JFBStatusInterface status;
//
//    private JFBActionInterface incrementalAction;
//
//    private JFBActionInterface goalAction;
//
//    private JFBResetInterface reset;
//
//    private JFBEventBindsInterface eventBinds;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public boolean isActivated();

    /**
     *
     **/
    public void setActivated(boolean activated_);

    /**
     *
     **/
    public int getValue();

    /**
     *
     **/
    public void setValue(int value_);

    /**
     *
     **/
    public int getSteps();

    /**
     *
     **/
    public void setSteps(int steps_);

    /**
     *
     **/
    public int getIncrementalValue();

    /**
     *
     **/
    public void setIncrementalValue(int incrementalValue_);

    /**
     *
     **/
    public JFBConditionInterface getCondition();

    /**
     *
     **/
    public void setCondition(JFBConditionInterface condition_);

    /**
     *
     **/
    public JFBStatusInterface getStatus();

    /**
     *
     **/
    public void setStatus(JFBStatusInterface status_);

    /**
     *
     **/
    public JFBActionInterface getIncrementalAction();

    /**
     *
     **/
    public void setIncrementalAction(JFBActionInterface incrementalAction_);

    /**
     *
     **/
    public JFBActionInterface getGoalAction();

    /**
     *
     **/
    public void setGoalAction(JFBActionInterface goalAction_);

    /**
     *
     **/
    public JFBResetInterface getReset();

    /**
     *
     **/
    public void setReset(JFBResetInterface reset_);

    /**
     *
     **/
    public JFBEventBindsInterface getEventBinds();

    /**
     *
     **/
    public void setEventBinds(JFBEventBindsInterface eventBinds_);

    /**
     *
     **/
    public boolean isObjectiveCandidate(JFBObjectiveInterface candidate);
    
    /**
    *
    **/
   public HashSet<? extends JFBObjectiveInterface> getObjectiveFamily() ;

   /**
    *
    **/
   public void setObjectiveFamily(HashSet<? extends JFBObjectiveInterface> objectiveFamily_) ;
   
   /**
   *
   **/
  public void setParent(JFBContainerInterface parent_) ;
  
  /**
  *
  **/
  public JFBContainerInterface parent() ;

}