/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.objectives;

import java.util.HashSet;

import com.jfbuilds.playngame.general.JFBActionInterface;
import com.jfbuilds.playngame.general.JFBConditionInterface;
import com.jfbuilds.playngame.general.JFBContainerInterface;
import com.jfbuilds.playngame.general.JFBEventBindsInterface;
import com.jfbuilds.playngame.general.JFBResetInterface;
import com.jfbuilds.playngame.general.JFBStatusInterface;

/**
 *
 **/
public interface JFBObjectiveInterface {

	/* ===================================== */
	/* == Member Variables == */
	/* ===================================== */

	// private boolean activated;
	//
	// private int value;
	//
	// private int steps;
	//
	// private int incrementalValue;
	//
	// private JFBConditionInterface condition;
	//
	// private JFBStatusInterface status;
	//
	// private JFBActionInterface incrementalAction;
	//
	// private JFBActionInterface goalAction;
	//
	// private JFBResetInterface reset;
	//
	// private JFBEventBindsInterface eventBinds;

	/* ===================================== */
	/* == Methods == */
	/* ===================================== */

	/**
	 *
	 **/
	public JFBConditionInterface getCondition();

	/**
	 *
	 **/
	public JFBEventBindsInterface getEventBinds();

	/**
	 *
	 **/
	public JFBActionInterface getGoalAction();

	/**
	 *
	 **/
	public JFBActionInterface getIncrementalAction();

	/**
	 *
	 **/
	public int getIncrementalValue();

	/**
	 *
	 **/
	public HashSet<? extends JFBObjectiveInterface> getObjectiveFamily();

	/**
	 *
	 **/
	public JFBResetInterface getReset();

	/**
	 *
	 **/
	public JFBStatusInterface getStatus();

	/**
	 *
	 **/
	public int getSteps();

	/**
	 *
	 **/
	public int getValue();

	/**
	 *
	 **/
	public boolean isActivated();

	/**
	 *
	 **/
	public boolean isObjectiveCandidate(JFBObjectiveInterface candidate);

	/**
	 *
	 **/
	public JFBContainerInterface parent();

	/**
	 *
	 **/
	public void setActivated(boolean activated_);

	/**
	 *
	 **/
	public void setCondition(JFBConditionInterface condition_);

	/**
	 *
	 **/
	public void setEventBinds(JFBEventBindsInterface eventBinds_);

	/**
	 *
	 **/
	public void setGoalAction(JFBActionInterface goalAction_);

	/**
	 *
	 **/
	public void setIncrementalAction(JFBActionInterface incrementalAction_);

	/**
	 *
	 **/
	public void setIncrementalValue(int incrementalValue_);

	/**
	 *
	 **/
	public void setObjectiveFamily(HashSet<? extends JFBObjectiveInterface> objectiveFamily_);

	/**
	 *
	 **/
	public void setParent(JFBContainerInterface parent_);

	/**
	 *
	 **/
	public void setReset(JFBResetInterface reset_);

	/**
	 *
	 **/
	public void setStatus(JFBStatusInterface status_);

	/**
	 *
	 **/
	public void setSteps(int steps_);

	/**
	 *
	 **/
	public void setValue(int value_);

}