/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.objectives;

/**
 *
 **/
public class SimpleFragmentObjective extends JFBAbstractFragmentObjective implements JFBFragmentObjectiveInterface {

}