/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public abstract class JFBAbstractReset implements JFBResetInterface {

	@Override
	public void reset(JFBContainerInterface parent) {
		// TODO Auto-generated method stub
		
	}

}