/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import java.util.ArrayList;

import playn.core.Game;
import playn.core.GroupLayer;

import com.jfbuilds.playngame.abilities.JFBGameAbilityInterface;
import com.jfbuilds.playngame.abilities.SimpleGameAbility;
import com.jfbuilds.playngame.objectives.JFBGameObjectiveInterface;
import com.jfbuilds.playngame.objectives.SimpleGameObjective;
import com.jfbuilds.playngame.scenes.JFBSceneInterface;
import com.jfbuilds.playngame.scenes.SimpleScene;

/**
 *
 **/
public abstract class JFBAbstractGame extends JFBAbstractContainer implements JFBGameInterface, JFBContainerInterface, Game {
	private GroupLayer base;
	private JFBSceneInterface currentScene; 
	private int currentSceneIndex;
	private ArrayList<? extends JFBGameAbilityInterface> gameAbilities;
	private ArrayList<? extends JFBGameObjectiveInterface> gameObjectives;
	private ArrayList<? extends JFBSceneInterface> gameScenes;
	

	/**
	 * @return the base
	 */
	public GroupLayer getBase() {
		return base;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getCurrectScene()
	 */
	@Override
	public JFBSceneInterface getCurrentScene() {
		if (this.getGameScenes()!= null) {
			return getGameScenes().get(this.currentSceneIndex);
		} else {
			System.out.println("No scenes are loaded for game.");
			return null;
		}
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getCurrentSceneIndex()
	 */
	@Override
	public int getCurrentSceneIndex() {
		return currentSceneIndex;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getGameAbilities()
	 */
	@Override
	public ArrayList<? extends JFBGameAbilityInterface> getGameAbilities() {
		return gameAbilities;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getGameObjectives()
	 */
	@Override
	public ArrayList<? extends JFBGameObjectiveInterface> getGameObjectives() {
		return gameObjectives;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getGameScenes()
	 */
	@Override
	public ArrayList<? extends JFBSceneInterface> getGameScenes() {
		return gameScenes;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	/**
	 * @param base the base to set
	 */
	synchronized public void setBase(GroupLayer base) {
		this.base = base;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setCurrectScene(com.jfbuilds.playngame.scenes.JFBSceneInterface)
	 */
	@Override
	public void setCurrentScene(JFBSceneInterface currentScene_) {
		currentScene = currentScene_;
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setCurrentSceneIndex(int)
	 */
	@Override
	synchronized public void setCurrentSceneIndex(int currentSceneIndex_) {
		currentSceneIndex = currentSceneIndex_;
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setGameAbilities(java.util.ArrayList)
	 */
	@Override
	public void setGameAbilities(ArrayList<? extends JFBGameAbilityInterface> gameAbilities_) {
		gameAbilities = gameAbilities_;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setGameObjectives(java.util.ArrayList)
	 */
	@Override
	public void setGameObjectives(ArrayList<? extends JFBGameObjectiveInterface> gameObjectives_) {
		gameObjectives = gameObjectives_;
	}
	
	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setGameScenes(java.util.ArrayList)
	 */
	@Override
	public void setGameScenes(ArrayList<? extends JFBSceneInterface> gameScenes_) {
		gameScenes = gameScenes_;
	}

	@Override
	public void tick(int elapsed) {
		// TODO Auto-generated method stub
		
	}
	
	

}