/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public abstract class JFBAbstractStatus implements JFBStatusInterface {

	@Override
	public String getStatus() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setStatus(String status_) {
		// TODO Auto-generated method stub

	}

}