/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import java.util.EventObject;

/**
 *
 **/
public abstract class JFBAbstractCondition implements JFBConditionInterface {

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBConditionInterface#evaluate(java.util.EventObject)
	 */
	@Override
	public void evaluate(EventObject event) {
		// TODO Auto-generated method stub
		
	}

}