/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public abstract class JFBAbstractAction implements JFBActionInterface {

	/*
	 * (non-Javadoc)
	 *
	 * @see com.jfbuilds.playngame.general.JFBActionInterface#execute()
	 */
	@Override
	public void execute() {
		// TODO Auto-generated method stub

	}

}