/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public abstract class JFBAbstractTransition implements JFBTransitionInterface {

	@Override
	public int getDurationInMilliSeconds() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int getSteps() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public boolean hasTransition() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void setDurationInMilliSeconds(int durationInMilliSeconds_) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setSteps(int steps_) {
		// TODO Auto-generated method stub

	}

	@Override
	public void setTransition(boolean transitionPresent_) {
		// TODO Auto-generated method stub

	}

	@Override
	public void transitionIn() {
		// TODO Auto-generated method stub

	}

	@Override
	public void transitionOut() {
		// TODO Auto-generated method stub

	}

}