/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import java.util.EventObject;

/**
 *
 **/
public interface JFBConditionInterface {

	/* ===================================== */
	/* == Member Variables == */
	/* ===================================== */

	/* ===================================== */
	/* == Methods == */
	/* ===================================== */

	/**
	 *
	 **/
	public void evaluate(EventObject event);

}