/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import java.util.ArrayList;
import java.util.HashSet;

import playn.core.GroupLayer;
import playn.core.Layer;

import com.jfbuilds.playngame.abilities.JFBAbilityInterface;
import com.jfbuilds.playngame.exceptions.AbilityImplementationException;
import com.jfbuilds.playngame.exceptions.ContainerImplementationException;
import com.jfbuilds.playngame.exceptions.InvalidSetGetException;
import com.jfbuilds.playngame.exceptions.ObjectiveImplementationException;
import com.jfbuilds.playngame.objectives.JFBObjectiveInterface;

/**
 *
 **/
public interface JFBContainerInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */
	
	

//    private ArrayList<? extends JFBContainerInterface> containerFamily;
//
//    private HashSet<? extends JFBAbilityInterface> abilityFamily;
//
//    private HashSet<? extends JFBObjectiveInterface> objectiveFamily;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

	/** 
     *    create a new instance
     **/
    public void create();
    
    /** 
     *    create a new instance
     **/
    public void init();

    /** 
     *    play current instance
     **/
    public void play();

    /**
     *    change to next instance in container family if allowed
     **/
    public void next();

    /**
     *    pause the current instance
     **/
    public void pause();

    /**
     *    resume the current instance if paused
     **/
    public void resume();

    /**
     *    load an instance from a saved state
     **/
    public void load();
    
    /**
     *    save the instance to a saved state
     **/
    public void save();

    /**
     *   destroy the instance and close resources
     **/
    public void destroy();
    
    /**
     *   get the parent container
     **/
    public JFBContainerInterface parent();
    
    /**
     *   set the parent container
     **/
    public void setParent(JFBContainerInterface parent_);

    /**
     *
     **/
    public ArrayList<? extends JFBContainerInterface> getContainerFamily();

    /**
     *
     **/
    public void setContainerFamily(ArrayList<? extends JFBContainerInterface> containerFamily_);

    /**
     *
     **/
    public void addContainer(JFBContainerInterface container_) throws ContainerImplementationException ;

    /**
     *
     **/
    public void removeContainer(JFBContainerInterface container_) ;

    /**
     *
     **/
    public void addAbility(JFBAbilityInterface ability_) throws AbilityImplementationException ;

    /**
     *
     **/
    public void removeAbility(JFBAbilityInterface ability_) ;

    /**
     *
     **/
    public void addObjective(JFBObjectiveInterface objective_) throws ObjectiveImplementationException ;

    /**
     *
     **/
    public void removeObjective(JFBObjectiveInterface objective_) ;

    /**
     *
     **/
    public boolean isContainerCandidate(JFBContainerInterface candidate) ;
    
    /** 
     *    set base groupLayer for container visuals
     **/
    public void setBase(GroupLayer layer);
    
    /** 
     *    get base GroupLayer for container visuals
     **/
    public GroupLayer getBase();
    
    /** 
     *    print info for layer composition
     **/
    public void printBaseInfo();
    
    /** 
     *    add a layer from base
     **/
    public Layer addLayer(Layer layer);
    
    /** 
     *    remove a layer from base
     **/
    public Layer removeLayer();
    
    /** 
     *    get name of container
     **/
    public String getName();
    
    /** 
     *    set name of container
     **/
    public void setName(String name);
    
    /** 
     *    initialize the base to root or groupLayer
     **/
    public void initBase();

	int getContentIndex();

	void setContentIndex(int contentIndex_);
	
	/**
	 * @return the containers
	 */
	public ArrayList<JFBContainerInterface> getContainers() ;
	
	/**
	 * @param containers the containers to set
	 */
	public void setContainers(ArrayList<JFBContainerInterface> containers) ;
	
	/**
	 * @return the abilities
	 */
	public HashSet<JFBAbilityInterface> getAbilities() ;
	
	/**
	 * @param abilities the abilities to set
	 */
	public void setAbilities(HashSet<JFBAbilityInterface> abilities) ;
	
	/**
	 * @return the objectives
	 */
	public HashSet<JFBObjectiveInterface> getObjectives();
	
	/**
	 * @param objectives the objectives to set
	 */
	public void setObjectives(HashSet<JFBObjectiveInterface> objectives) ;
    
    
    

}