/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import java.util.ArrayList;
import java.util.HashSet;

import com.jfbuilds.playngame.abilities.JFBAbilityInterface;
import com.jfbuilds.playngame.abilities.JFBGameAbilityInterface;
import com.jfbuilds.playngame.objectives.JFBGameObjectiveInterface;
import com.jfbuilds.playngame.objectives.JFBObjectiveInterface;
import com.jfbuilds.playngame.scenes.JFBSceneInterface;

/**
 *
 **/
public interface JFBGameInterface extends JFBContainerInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    private ArrayList<JFBSceneInterface> gameScenes;
//
//    private ArrayList<JFBGameAbilityInterface> gameAbilities;
//
//    private ArrayList<JFBGameObjectives> gameObjectives;
//
//    private JFBSceneInterface currectScene;
//
//    private int currentSceneIndex;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public HashSet<JFBAbilityInterface> getGameAbilities() ;

    /**
     *
     **/
    public void setGameAbilities(HashSet<JFBAbilityInterface> gameAbilities_) ;

    /**
     *
     **/
    public ArrayList<JFBContainerInterface> getGameScenes() ;

    /**
     *
     **/
    public void setGameScenes(ArrayList<JFBContainerInterface> gameScenes_) ;

    /**
     *
     **/
    public HashSet<JFBObjectiveInterface> getGameObjectives() ;

    /**
     *
     **/
    public void setGameObjectives(HashSet<JFBObjectiveInterface> gameObjectives_) ;

    /**
     *
     **/
    public JFBSceneInterface getCurrentScene() ;

    /**
    *
    **/
   public void setCurrentScene(JFBSceneInterface currentScene_) ;
   
   /**
   *
   **/
  public void initScenes() ;
  
  /**
  *
  **/
 public void createScenes() ;
    
    

}