/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public interface JFBPositionInterface {

	/* ===================================== */
	/* == Member Variables == */
	/* ===================================== */

	// private float xPostion;
	//
	// private float yPosition;
	//
	// private float zPosition;
	//
	// private float xScale;
	//
	// private float yScale;
	//
	// private float zScale;
	//
	// private float alpha;

	/* ===================================== */
	/* == Methods == */
	/* ===================================== */

	/**
	 *
	 **/
	public float getAlpha();

	/**
	 *
	 **/
	public float getXPostion();

	/**
	 *
	 **/
	public float getXScale();

	/**
	 *
	 **/
	public float getYPosition();

	/**
	 *
	 **/
	public float getYScale();

	/**
	 *
	 **/
	public float getZPosition();

	/**
	 *
	 **/
	public float getZScale();

	/**
	 *
	 **/
	public void setAlpha(float alpha_);

	/**
	 *
	 **/
	public void setXPostion(float xPostion_);

	/**
	 *
	 **/
	public void setXScale(float xScale_);

	/**
	 *
	 **/
	public void setYPosition(float yPosition_);

	/**
	 *
	 **/
	public void setYScale(float yScale_);

	/**
	 *
	 **/
	public void setZPosition(float zPosition_);

	/**
	 *
	 **/
	public void setZScale(float zScale_);

}