/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public interface JFBResetInterface {

	/* ===================================== */
	/* == Member Variables == */
	/* ===================================== */

	/* ===================================== */
	/* == Methods == */
	/* ===================================== */

	/**
	 *
	 **/
	public void reset(JFBContainerInterface parent);

}