/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public interface JFBStatusInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    private String  status;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public String getStatus() ;

    /**
     *
     **/
    public void setStatus(String  status_) ;

}