/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public interface JFBTransitionInterface {

	/* ===================================== */
	/* == Member Variables == */
	/* ===================================== */

	// private boolean transitionPresent;
	//
	// private int durationInMilliSeconds;
	//
	// private int steps;

	/* ===================================== */
	/* == Methods == */
	/* ===================================== */

	/**
	 *
	 **/
	public int getDurationInMilliSeconds();

	/**
	 *
	 **/
	public int getSteps();

	/**
	 *
	 **/
	public boolean hasTransition();

	/**
	 *
	 **/
	public void setDurationInMilliSeconds(int durationInMilliSeconds_);

	/**
	 *
	 **/
	public void setSteps(int steps_);

	/**
	 *
	 **/
	public void setTransition(boolean transitionPresent_);

	/**
	 *
	 **/
	public void transitionIn();

	/**
	 *
	 **/
	public void transitionOut();

}