/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import static playn.core.PlayN.assets;
import static playn.core.PlayN.graphics;

import java.util.ArrayList;

import com.jfbuilds.playngame.exceptions.ContainerImplementationException;
import com.jfbuilds.playngame.scenes.Act1Scene;
import com.jfbuilds.playngame.scenes.Act2Scene;
import com.jfbuilds.playngame.scenes.Act3Scene;
import com.jfbuilds.playngame.scenes.Act4Scene;
import com.jfbuilds.playngame.scenes.Act5Scene;
import com.jfbuilds.playngame.scenes.Act6Scene;
import com.jfbuilds.playngame.scenes.Act7Scene;
import com.jfbuilds.playngame.scenes.ClosingActScene;
import com.jfbuilds.playngame.scenes.OpeningActScene;
import com.jfbuilds.playngame.scenes.SimpleScene;

import playn.core.GroupLayer;
import playn.core.Image;
import playn.core.ImageLayer;

/**
 *
 **/
public class Zankie extends SimpleGame {

	public Zankie() {
		super(33);
		System.out.println("Game created..");
	}
	
	@Override
	public void init() {
		super.init();
		setName("Zankie GameOn!");
		System.out.print("Zankie is On!!! ");
	}
@Override
public void createScenes() {

		try {
			this.addContainer(new OpeningActScene("Opening Act", this));
			this.addContainer(new Act1Scene("Act 1", this));
			this.addContainer(new Act2Scene("Act 2", this));
			this.addContainer(new Act3Scene("Act 3", this));
			this.addContainer(new Act4Scene("Act 4", this));
			this.addContainer(new Act5Scene("Act 5", this));
			this.addContainer(new Act6Scene("Act 6", this));
			this.addContainer(new Act7Scene("Act 7", this));
			this.addContainer(new ClosingActScene("Closing Act", this));
		} catch (ContainerImplementationException e) {
			e.getMessage();
			e.printStackTrace();
		}
	}


	@Override
	public void paint(float alpha) {
		// the background automatically paints itself, so no need to do anything
		// here!
	}

}