/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.fragments;

import com.jfbuilds.playngame.general.JFBAbstractContainer;
import com.jfbuilds.playngame.general.JFBActionInterface;
import com.jfbuilds.playngame.general.JFBConditionInterface;
import com.jfbuilds.playngame.general.JFBEventBindsInterface;
import com.jfbuilds.playngame.general.JFBPositionInterface;
import com.jfbuilds.playngame.general.JFBTransitionInterface;

/**
 *
 **/
public abstract class JFBAbstractFragment extends JFBAbstractContainer implements JFBFragmentInterface {

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#getFragmentType()
	 */
	@Override
	public FragmentType getFragmentType() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#setFragmentType(com.jfbuilds.playngame.fragments.JFBFragmentInterface.FragmentType)
	 */
	@Override
	public void setFragmentType(FragmentType fragmentType_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#getStartPosition()
	 */
	@Override
	public JFBPositionInterface getStartPosition() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#setStartPosition(com.jfbuilds.playngame.general.JFBPositionInterface)
	 */
	@Override
	public void setStartPosition(JFBPositionInterface startPosition_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#getEndPostion()
	 */
	@Override
	public JFBPositionInterface getEndPostion() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#setEndPostion(com.jfbuilds.playngame.general.JFBPositionInterface)
	 */
	@Override
	public void setEndPostion(JFBPositionInterface endPostion_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#getTransition()
	 */
	@Override
	public JFBTransitionInterface getTransition() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#setTransition(com.jfbuilds.playngame.general.JFBTransitionInterface)
	 */
	@Override
	public void setTransition(JFBTransitionInterface transition_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#getAction()
	 */
	@Override
	public JFBActionInterface getAction() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#setAction(com.jfbuilds.playngame.general.JFBActionInterface)
	 */
	@Override
	public void setAction(JFBActionInterface action_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#getCondition()
	 */
	@Override
	public JFBConditionInterface getCondition() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#setCondition(com.jfbuilds.playngame.general.JFBConditionInterface)
	 */
	@Override
	public void setCondition(JFBConditionInterface condition_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#getEventBinds()
	 */
	@Override
	public JFBEventBindsInterface getEventBinds() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.fragments.JFBFragmentInterface#setEventBinds(com.jfbuilds.playngame.general.JFBEventBindsInterface)
	 */
	@Override
	public void setEventBinds(JFBEventBindsInterface eventBinds_) {
		// TODO Auto-generated method stub
		
	}

}