/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.fragments;

import com.jfbuilds.playngame.general.JFBActionInterface;
import com.jfbuilds.playngame.general.JFBConditionInterface;
import com.jfbuilds.playngame.general.JFBContainerInterface;
import com.jfbuilds.playngame.general.JFBEventBindsInterface;
import com.jfbuilds.playngame.general.JFBPositionInterface;
import com.jfbuilds.playngame.general.JFBTransitionInterface;

/**
 *
 **/
public interface JFBFragmentInterface extends JFBContainerInterface {
	
	
    /* ===================================== */
    /* ==        FragmentType enum        == */
    /* ===================================== */
	
	public enum FragmentType {
		SIMPLE_FRAGMENT (1000, true, 100114),
		CONTROLABLE_CHARACTER (2000, false, 100114),
		NONCONTROLABLE_CHARACTER (2010, true, 100114),
		BACKGROUND_LAYER (3000, false, 100114),
		FORGROUND_LAYER (3010, false, 100114),
		WALKABLE_MAP  (4000, false, 100114),
		SWIMMABLE_MAP (4050, false, 100114);
		
		private final int id;
		private final boolean multipleAllowed;
		private final int creationStamp;
		
		FragmentType(int id_, boolean multipleAllowed_, int creationStamp_) {
			id = id_;
			multipleAllowed = multipleAllowed_;
			creationStamp = creationStamp_;
		}
		
		public int id() {
			return id;
		}
		
		public boolean multipleAllowed() {
			return multipleAllowed;
		}
		
		public int creationStamp() {
			return creationStamp;
		}
		
		public String toString() {
			return String.valueOf(multipleAllowed());
		}
	}
	
	
    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    FragmentType fragmentType = FragmentType.SIMPLE_FRAGMENT;
//
//    JFBPositionInterface startPosition = null;
//
//    JFBPositionInterface endPostion = null;
//
//    JFBTransitionInterface transition = null;
//
//    JFBActionInterface action = null;
//
//    JFBConditionInterface condition = null;
//
//    JFBEventBindsInterface eventBinds = null;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public FragmentType getFragmentType();

    /**
     *
     **/
    public void setFragmentType(FragmentType fragmentType_);

    /**
     *
     **/
    public JFBPositionInterface getStartPosition();

    /**
     *
     **/
    public void setStartPosition(JFBPositionInterface startPosition_);

    /**
     *
     **/
    public JFBPositionInterface getEndPostion();

    /**
     *
     **/
    public void setEndPostion(JFBPositionInterface endPostion_);

    /**
     *
     **/
    public JFBTransitionInterface getTransition();

    /**
     *
     **/
    public void setTransition(JFBTransitionInterface transition_);

    /**
     *
     **/
    public JFBActionInterface getAction();

    /**
     *
     **/
    public void setAction(JFBActionInterface action_);

    /**
     *
     **/
    public JFBConditionInterface getCondition();

    /**
     *
     **/
    public void setCondition(JFBConditionInterface condition_);

    /**
     *
     **/
    public JFBEventBindsInterface getEventBinds();

    /**
     *
     **/
    public void setEventBinds(JFBEventBindsInterface eventBinds_);

}