/* Generated by Quick UML for Java */

package playn.core;

/**
 *
 **/
public class Game.Default implements Game {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private   ;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public Game.Default(int updateRate) {

    }

    /**
     *
     **/
    public void paint(float alpha) {

    }

    /**
     *
     **/
    public void update(int delta) {

    }

}