/* Generated by Quick UML for Java */

package playn.core;

/**
 *
 **/
public interface Game {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private    ;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public void init() {

    }

    /**
     *
     **/
    public void tick(int elapsed) {

    }

}