/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

/**
 *
 **/
public interface JFBSceneInterface extends JFBContainerInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private ArrayList<JFBSceneObjectiveInterface> sceneObjectives;

    private ArrayList<JFBSceneAbilityInterface> sceneAbilities;

    private ArrayList<JFBFragmentInterface> sceneFragments;

    private JFBTransitionInterface transition;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public ArrayList<JFBSceneObjectiveInterface> getSceneObjectives() {
        return sceneObjectives;
    }

    /**
     *
     **/
    public void setSceneObjectives(ArrayList<JFBSceneObjectiveInterface> sceneObjectives_) {
        sceneObjectives = sceneObjectives_;
    }

    /**
     *
     **/
    public ArrayList<JFBFragmentInterface> getSceneFragments() {
        return sceneFragments;
    }

    /**
     *
     **/
    public void setSceneFragments(ArrayList<JFBFragmentInterface> sceneFragments_) {
        sceneFragments = sceneFragments_;
    }

    /**
     *
     **/
    public ArrayList<JFBSceneAbilityInterface> getSceneAbilities() {
        return sceneAbilities;
    }

    /**
     *
     **/
    public void setSceneAbilities(ArrayList<JFBSceneAbilityInterface> sceneAbilities_) {
        sceneAbilities = sceneAbilities_;
    }

    /**
     *
     **/
    public JFBTransitionInterface getTransition() {
        return transition;
    }

    /**
     *
     **/
    public void setTransition(JFBTransitionInterface transition_) {
        transition = transition_;
    }

}