/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.exceptions;

import java.io.Serializable;

/**
 *
 **/
public class ContainerImplementationException extends ImplementationException implements Serializable {

}