/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.exceptions;

import java.lang.Exception;
import java.io.Serializable;

/**
 *
 **/
public class JFBException extends Exception implements Serializable {

}