/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.abilities;

import com.jfbuilds.playngame.general.JFBActionInterface;
import com.jfbuilds.playngame.general.JFBConditionInterface;
import com.jfbuilds.playngame.general.JFBDisplayInterface;
import com.jfbuilds.playngame.general.JFBEventBindsInterface;
import com.jfbuilds.playngame.general.JFBResetInterface;

/**
 *
 **/
public class SimpleSceneAbility extends JFBAbstractSceneAbility implements JFBSceneAbilityInterface {

	@Override
	public boolean isActivated() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void setActivated(boolean activated_) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public int getValue() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void setValue(int value_) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public JFBConditionInterface getCondition() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setCondition(JFBConditionInterface condition_) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public JFBActionInterface getAction() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setAction(JFBActionInterface action_) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public JFBDisplayInterface getDisplay() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setDisplay(JFBDisplayInterface display_) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public JFBResetInterface getReset() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setReset(JFBResetInterface reset_) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public JFBEventBindsInterface getEventBinds() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setEventBinds(JFBEventBindsInterface eventBinds_) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public boolean isAbilityCandidate(JFBAbilityInterface candidate) {
		// TODO Auto-generated method stub
		return false;
	}

}