/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import java.util.ArrayList;

import com.jfbuilds.playngame.abilities.JFBGameAbilityInterface;
import com.jfbuilds.playngame.objectives.JFBGameObjectiveInterface;
import com.jfbuilds.playngame.scenes.JFBSceneInterface;

//import playn.core.Game;
//import playn.core.Game.Default;

/**
 *
 **/
public abstract class JFBAbstractGame extends JFBAbstractContainer implements JFBGameInterface {

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getGameAbilities()
	 */
	@Override
	public ArrayList<? extends JFBGameAbilityInterface> getGameAbilities() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setGameAbilities(java.util.ArrayList)
	 */
	@Override
	public void setGameAbilities(ArrayList<? extends JFBGameAbilityInterface> gameAbilities_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getGameScenes()
	 */
	@Override
	public ArrayList<? extends JFBSceneInterface> getGameScenes() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setGameScenes(java.util.ArrayList)
	 */
	@Override
	public void setGameScenes(ArrayList<? extends JFBSceneInterface> gameScenes_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getGameObjectives()
	 */
	@Override
	public ArrayList<? extends JFBGameObjectiveInterface> getGameObjectives() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setGameObjectives(java.util.ArrayList)
	 */
	@Override
	public void setGameObjectives(ArrayList<? extends JFBGameObjectiveInterface> gameObjectives_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#createGame()
	 */
	@Override
	public void createGame() {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#destroyGame()
	 */
	@Override
	public void destroyGame() {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#loadGame()
	 */
	@Override
	public void loadGame() {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#saveGame()
	 */
	@Override
	public void saveGame() {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#pauseGame()
	 */
	@Override
	public void pauseGame() {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getCurrectScene()
	 */
	@Override
	public JFBSceneInterface getCurrectScene() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setCurrectScene(com.jfbuilds.playngame.scenes.JFBSceneInterface)
	 */
	@Override
	public void setCurrectScene(JFBSceneInterface currectScene_) {
		// TODO Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#getCurrentSceneIndex()
	 */
	@Override
	public int getCurrentSceneIndex() {
		// TODO Auto-generated method stub
		return 0;
	}

	/* (non-Javadoc)
	 * @see com.jfbuilds.playngame.general.JFBGameInterface#setCurrentSceneIndex(int)
	 */
	@Override
	public void setCurrentSceneIndex(int currentSceneIndex_) {
		// TODO Auto-generated method stub
		
	}

}