/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import java.util.ArrayList;
import java.util.HashSet;

import com.jfbuilds.playngame.abilities.JFBAbilityInterface;
import com.jfbuilds.playngame.exceptions.AbilityImplementationException;
import com.jfbuilds.playngame.exceptions.ContainerImplementationException;
import com.jfbuilds.playngame.exceptions.ObjectiveImplementationException;
import com.jfbuilds.playngame.objectives.JFBObjectiveInterface;

/**
 *
 **/
public interface JFBContainerInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    private ArrayList<? extends JFBContainerInterface> containerFamily;
//
//    private HashSet<? extends JFBAbilityInterface> abilityFamily;
//
//    private HashSet<? extends JFBObjectiveInterface> objectiveFamily;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public void create();

    /**
     *
     **/
    public void play();

    /**
     *
     **/
    public void next();

    /**
     *
     **/
    public void pause();

    /**
     *
     **/
    public void resume();

    /**
     *
     **/
    public void load();

    /**
     *
     **/
    public void destroy();

    /**
     *
     **/
    public ArrayList<? extends JFBContainerInterface> getContainerFamily();

    /**
     *
     **/
    public void setContainerFamily(ArrayList<? extends JFBContainerInterface> containerFamily_);

    /**
     *
     **/
    public void addContainer(JFBContainerInterface container_) throws ContainerImplementationException ;

    /**
     *
     **/
    public void removeContainer(JFBContainerInterface container_) ;

    /**
     *
     **/
    public HashSet<? extends JFBAbilityInterface> getAbilityFamily() ;

    /**
     *
     **/
    public void setAbilityFamily(HashSet<? extends JFBAbilityInterface> abilityFamily_) ;

    /**
     *
     **/
    public void addAbility(JFBAbilityInterface ability_) throws AbilityImplementationException ;

    /**
     *
     **/
    public void removeAbility(JFBAbilityInterface ability_) ;

    /**
     *
     **/
    public HashSet<? extends JFBObjectiveInterface> getObjectiveFamily() ;

    /**
     *
     **/
    public void setObjectiveFamily(HashSet<? extends JFBObjectiveInterface> objectiveFamily_) ;

    /**
     *
     **/
    public void addObjective(JFBObjectiveInterface objective_) throws ObjectiveImplementationException ;

    /**
     *
     **/
    public void removeObjective(JFBObjectiveInterface objective_) ;

    /**
     *
     **/
    public boolean isContainerCandidate(JFBContainerInterface candidate) ;

}