/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import java.util.ArrayList;

import com.jfbuilds.playngame.abilities.JFBGameAbilityInterface;
import com.jfbuilds.playngame.objectives.JFBGameObjectiveInterface;
import com.jfbuilds.playngame.scenes.JFBSceneInterface;

/**
 *
 **/
public interface JFBGameInterface extends JFBContainerInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    private ArrayList<JFBSceneInterface> gameScenes;
//
//    private ArrayList<JFBGameAbilityInterface> gameAbilities;
//
//    private ArrayList<JFBGameObjectives> gameObjectives;
//
//    private JFBSceneInterface currectScene;
//
//    private int currentSceneIndex;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public ArrayList<? extends JFBGameAbilityInterface> getGameAbilities() ;

    /**
     *
     **/
    public void setGameAbilities(ArrayList<? extends JFBGameAbilityInterface> gameAbilities_) ;

    /**
     *
     **/
    public ArrayList<? extends JFBSceneInterface> getGameScenes() ;

    /**
     *
     **/
    public void setGameScenes(ArrayList<? extends JFBSceneInterface> gameScenes_) ;

    /**
     *
     **/
    public ArrayList<? extends JFBGameObjectiveInterface> getGameObjectives() ;

    /**
     *
     **/
    public void setGameObjectives(ArrayList<? extends JFBGameObjectiveInterface> gameObjectives_) ;

    /**
     *
     **/
    public void createGame() ;

    /**
     *
     **/
    public void destroyGame() ;

    /**
     *
     **/
    public void loadGame() ;

    /**
     *
     **/
    public void saveGame() ;

    /**
     *
     **/
    public void pauseGame() ;

    /**
     *
     **/
    public JFBSceneInterface getCurrectScene() ;

    /**
     *
     **/
    public void setCurrectScene(JFBSceneInterface currectScene_) ;

    /**
     *
     **/
    public int getCurrentSceneIndex() ;

    /**
     *
     **/
    public void setCurrentSceneIndex(int currentSceneIndex_) ;

}