/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public interface JFBPositionInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    private float xPostion;
//
//    private float yPosition;
//
//    private float zPosition;
//
//    private float xScale;
//
//    private float yScale;
//
//    private float zScale;
//
//    private float alpha;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public float getXPostion();

    /**
     *
     **/
    public void setXPostion(float xPostion_);

    /**
     *
     **/
    public float getYPosition();

    /**
     *
     **/
    public void setYPosition(float yPosition_);

    /**
     *
     **/
    public float getZPosition();

    /**
     *
     **/
    public void setZPosition(float zPosition_);

    /**
     *
     **/
    public float getXScale();

    /**
     *
     **/
    public void setXScale(float xScale_);

    /**
     *
     **/
    public float getYScale();

    /**
     *
     **/
    public void setYScale(float yScale_);

    /**
     *
     **/
    public float getZScale();

    /**
     *
     **/
    public void setZScale(float zScale_);

    /**
     *
     **/
    public float getAlpha();

    /**
     *
     **/
    public void setAlpha(float alpha_);

}