/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public interface JFBTransitionInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    private boolean transitionPresent;
//
//    private int durationInMilliSeconds;
//
//    private int steps;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public boolean hasTransition() ;

    /**
     *
     **/
    public void setTransition(boolean transitionPresent_) ;

    /**
     *
     **/
    public int getDurationInMilliSeconds() ;

    /**
     *
     **/
    public void setDurationInMilliSeconds(int durationInMilliSeconds_) ;
    
    /**
     *
     **/
    public void transitionIn() ;

    /**
     *
     **/
    public void transitionOut() ;

    /**
     *
     **/
    public int getSteps() ;

    /**
     *
     **/
    public void setSteps(int steps_) ;

}