/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import playn.core.Game;;
import playn.core.Game.Default;

/**
 *
 **/
public class JFBAbstractGame extends Game.Default implements JFBGameInterface {

}