/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public interface JFBContainerInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private ArrayList<? extends JFBContainerInterface> containerFamily;

    private HashSet<? extends JFBAbilityInterface> abilityFamily;

    private HashSet<? extends JFBObjectiveInterface> objectiveFamily;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public void create() {

    }

    /**
     *
     **/
    public void play() {

    }

    /**
     *
     **/
    public void next() {

    }

    /**
     *
     **/
    public void pause() {

    }

    /**
     *
     **/
    public void resume() {

    }

    /**
     *
     **/
    public void load() {

    }

    /**
     *
     **/
    public void destroy() {

    }

    /**
     *
     **/
    public ArrayList<? extends JFBContainerInterface> getContainerFamily() {
        return containerFamily;
    }

    /**
     *
     **/
    public void setContainerFamily(ArrayList<? extends) {
        containerFamily = containerFamily_;
    }

    /**
     *
     **/
    public void addContainer(JFBContainerInterface container_) throws ContainerImplementationException {
        // fill me in
    }

    /**
     *
     **/
    public void removeContainer(JFBContainerInterface container_) {
        // fill me in
    }

    /**
     *
     **/
    public HashSet<? extends JFBAbilityInterface> getAbilityFamily() {
        return abilityFamily;
    }

    /**
     *
     **/
    public void setAbilityFamily(HashSet<? extends) {
        abilityFamily = abilityFamily_;
    }

    /**
     *
     **/
    public void addAbility(JFBAbilityInterface ability_) throws AbilityImplmentationException {
        // fill me in
    }

    /**
     *
     **/
    public void removeAbility(JFBAbilityInterface ability_) {
        // fill me in
    }

    /**
     *
     **/
    public HashSet<? extends JFBObjectiveInterface> getObjectiveFamily() {
        return objectiveFamily;
    }

    /**
     *
     **/
    public void setObjectiveFamily(HashSet<? extends) {
        objectiveFamily = objectiveFamily_;
    }

    /**
     *
     **/
    public void addObjective(JFBObjectiveInterface objective_) throws ObjectiveImplementationException {
        // fill me in
    }

    /**
     *
     **/
    public void removeObjective(JFBObjectiveInterface objective_) {
        // fill me in
    }

    /**
     *
     **/
    public boolean isContainerCandidate(JFBContainerInterface candidate) {

    }

}