/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

import java.awt.EventObject;

/**
 *
 **/
public class JFBConditionInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private   ;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public void evaluate(EventObject event) {

    }

}