/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public class JFBDisplayInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private   ;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public void paint(int zIndex) {

    }

}