/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public interface JFBPositionInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private float xPostion;

    private float yPosition;

    private float zPosition;

    private float xScale;

    private float yScale;

    private float zScale;

    private float alpha;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public float getXPostion() {
        return xPostion;
    }

    /**
     *
     **/
    public void setXPostion(float xPostion_) {
        xPostion = xPostion_;
    }

    /**
     *
     **/
    public float getYPosition() {
        return yPosition;
    }

    /**
     *
     **/
    public void setYPosition(float yPosition_) {
        yPosition = yPosition_;
    }

    /**
     *
     **/
    public float getZPosition() {
        return zPosition;
    }

    /**
     *
     **/
    public void setZPosition(float zPosition_) {
        zPosition = zPosition_;
    }

    /**
     *
     **/
    public float getXScale() {
        return xScale;
    }

    /**
     *
     **/
    public void setXScale(float xScale_) {
        xScale = xScale_;
    }

    /**
     *
     **/
    public float getYScale() {
        return yScale;
    }

    /**
     *
     **/
    public void setYScale(float yScale_) {
        yScale = yScale_;
    }

    /**
     *
     **/
    public float getZScale() {
        return zScale;
    }

    /**
     *
     **/
    public void setZScale(float zScale_) {
        zScale = zScale_;
    }

    /**
     *
     **/
    public float getAlpha() {
        return alpha;
    }

    /**
     *
     **/
    public void setAlpha(float alpha_) {
        alpha = alpha_;
    }

}