/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public class JFBResetInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private   ;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public void reset(JFBContainerInterface parent) {

    }

}