/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public class JFBStatusInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private String  status;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public String get status() {
        return  status;
    }

    /**
     *
     **/
    public void set status(String  status_) {
         status =  status_;
    }

}