/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.general;

/**
 *
 **/
public interface JFBTransitionInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private boolean transitionPresent;

    private int durationInMilliSeconds;

    private int steps;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public boolean hasTransition() {
        return transitionPresent;
    }

    /**
     *
     **/
    public void setTransition(boolean transitionPresent_) {
        transition = transition_;
    }

    /**
     *
     **/
    public int getDurationInMilliSeconds() {
        return durationInMilliSeconds;
    }

    /**
     *
     **/
    public void setDurationInMilliSeconds(int durationInMilliSeconds_) {
        durationInMilliSeconds = durationInMilliSeconds_;
    }

    /**
     *
     **/
    public void transitionIn() {

    }

    /**
     *
     **/
    public void transitionOut() {

    }

    /**
     *
     **/
    public int getSteps() {
        return steps;
    }

    /**
     *
     **/
    public void setSteps(int steps_) {
        steps = steps_;
    }

}