/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.abilities;

/**
 *
 **/
public interface JFBAbilityInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private boolean activated;

    private int value;

    private JFBEventBindsInterface eventBinds;

    private JFBConditionInterface condition;

    private JFBActionInterface action;

    private JFBDisplayInterface display;

    private JFBResetInterface reset;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public boolean isActivated() {
        return activated;
    }

    /**
     *
     **/
    public void setActivated(boolean activated_) {
        activated = activated_;
    }

    /**
     *
     **/
    public int getValue() {
        return value;
    }

    /**
     *
     **/
    public void setValue(int value_) {
        value = value_;
    }

    /**
     *
     **/
    public JFBConditionInterface getCondition() {
        return condition;
    }

    /**
     *
     **/
    public void setCondition(JFBConditionInterface condition_) {
        condition = condition_;
    }

    /**
     *
     **/
    public JFBActionInterface getAction() {
        return action;
    }

    /**
     *
     **/
    public void setAction(JFBActionInterface action_) {
        action = action_;
    }

    /**
     *
     **/
    public JFBDisplayInterface getDisplay() {
        return display;
    }

    /**
     *
     **/
    public void setDisplay(JFBDisplayInterface display_) {
        display = display_;
    }

    /**
     *
     **/
    public JFBResetInterface getReset() {
        return reset;
    }

    /**
     *
     **/
    public void setReset(JFBResetInterface reset_) {
        reset = reset_;
    }

    /**
     *
     **/
    public JFBEventBindsInterface getEventBinds() {
        return eventBinds;
    }

    /**
     *
     **/
    public void setEventBinds(JFBEventBindsInterface eventBinds_) {
        eventBinds = eventBinds_;
    }

    /**
     *
     **/
    public boolean isAbilityCandidate(JFBAbilityInterface candidate) {

    }

}