/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

import java.util.ArrayList;

import com.jfbuilds.playngame.abilities.JFBSceneAbilityInterface;
import com.jfbuilds.playngame.fragments.JFBFragmentInterface;
import com.jfbuilds.playngame.general.JFBContainerInterface;
import com.jfbuilds.playngame.general.JFBTransitionInterface;
import com.jfbuilds.playngame.objectives.JFBSceneObjectiveInterface;

/**
 *
 **/
public interface JFBSceneInterface extends JFBContainerInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

//    private ArrayList<JFBSceneObjectiveInterface> sceneObjectives;
//
//    private ArrayList<JFBSceneAbilityInterface> sceneAbilities;
//
//    private ArrayList<JFBFragmentInterface> sceneFragments;
//
//    private JFBTransitionInterface transition;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public ArrayList<JFBSceneObjectiveInterface> getSceneObjectives() ;

    /**
     *
     **/
    public void setSceneObjectives(ArrayList<JFBSceneObjectiveInterface> sceneObjectives_);

    /**
     *
     **/
    public ArrayList<JFBFragmentInterface> getSceneFragments();

    /**
     *
     **/
    public void setSceneFragments(ArrayList<JFBFragmentInterface> sceneFragments_);

    /**
     *
     **/
    public ArrayList<JFBSceneAbilityInterface> getSceneAbilities();

    /**
     *
     **/
    public void setSceneAbilities(ArrayList<JFBSceneAbilityInterface> sceneAbilities_);

    /**
     *
     **/
    public JFBTransitionInterface getTransition();

    /**
     *
     **/
    public void setTransition(JFBTransitionInterface transition_);

}