/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.fragments;

/**
 *
 **/
public interface JFBFragmentInterface extends JFBContainerInterface {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    public FragmentType fragmentType;

    private JFBPostionInterface startPosition;

    private JFBPostionInterface endPostion;

    private JFBTransitionInterface transition;

    private JFBActionInterface action;

    private JFBConditionInterface condition;

    private JFBEventBindsInterface eventBinds;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public FragmentType getFragmentType() {
        return fragmentType;
    }

    /**
     *
     **/
    public void setFragmentType(FragmentType fragmentType_) {
        fragmentType = fragmentType_;
    }

    /**
     *
     **/
    public JFBPostionInterface getStartPosition() {
        return startPosition;
    }

    /**
     *
     **/
    public void setStartPosition(JFBPostionInterface startPosition_) {
        startPosition = startPosition_;
    }

    /**
     *
     **/
    public JFBPostionInterface getEndPostion() {
        return endPostion;
    }

    /**
     *
     **/
    public void setEndPostion(JFBPostionInterface endPostion_) {
        endPostion = endPostion_;
    }

    /**
     *
     **/
    public JFBTransitionInterface getTransition() {
        return transition;
    }

    /**
     *
     **/
    public void setTransition(JFBTransitionInterface transition_) {
        transition = transition_;
    }

    /**
     *
     **/
    public JFBActionInterface getAction() {
        return action;
    }

    /**
     *
     **/
    public void setAction(JFBActionInterface action_) {
        action = action_;
    }

    /**
     *
     **/
    public JFBConditionInterface getCondition() {
        return condition;
    }

    /**
     *
     **/
    public void setCondition(JFBConditionInterface condition_) {
        condition = condition_;
    }

    /**
     *
     **/
    public JFBEventBindsInterface getEventBinds() {
        return eventBinds;
    }

    /**
     *
     **/
    public void setEventBinds(JFBEventBindsInterface eventBinds_) {
        eventBinds = eventBinds_;
    }

}