/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.fragments.JFBFragmentInterface;

/**
 *
 **/
public class enum FragmentType {

    /* ===================================== */
    /* ==         Member Variables        == */
    /* ===================================== */

    private int id;

    private boolean multipleAllowed;

    private int creationStamp;

    /* ===================================== */
    /* ==         Methods                 == */
    /* ===================================== */

    /**
     *
     **/
    public int id() {
        return id;
    }

    /**
     *
     **/
    public boolean multipleAllowed() {
        return multipleAllowed;
    }

    /**
     *
     **/
    public int creationStamp() {
        return creationStamp;
    }

}