/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

import com.jfbuilds.playngame.general.JFBContainerInterface;

/**
 *
 **/
public class AnimationMovie extends SimpleMovieScene implements JFBSceneInterface {

	public AnimationMovie(String name_, JFBContainerInterface parent_) {
		super(name_, parent_);
	}

}