/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

/**
 *
 **/
public class AnimationMovie extends SimpleMovieScene implements JFBSceneInterface {

	public AnimationMovie(String name_) {
		super(name_);
		// TODO Auto-generated constructor stub
	}

}