/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

import com.jfbuilds.playngame.general.JFBContainerInterface;

/**
 *
 **/
public class HiddenObjectsStage extends SimpleStageScene implements JFBSceneInterface {

	public HiddenObjectsStage(String name_, JFBContainerInterface parent_) {
		super(name_, parent_);
	}
	
}