/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

/**
 *
 **/
public class HiddenObjectsStage extends SimpleStageScene implements JFBSceneInterface {

	public HiddenObjectsStage(String name_) {
		super(name_);
		// TODO Auto-generated constructor stub
	}

}