/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

import static playn.core.PlayN.graphics;

import java.util.ArrayList;

import playn.core.GroupLayer;

import com.jfbuilds.playngame.abilities.JFBSceneAbilityInterface;
import com.jfbuilds.playngame.fragments.JFBFragmentInterface;
import com.jfbuilds.playngame.general.JFBAbstractContainer;
import com.jfbuilds.playngame.general.JFBTransitionInterface;
import com.jfbuilds.playngame.objectives.JFBSceneObjectiveInterface;

/**
 *
 **/
public abstract class JFBAbstractScene extends JFBAbstractContainer implements JFBSceneInterface {

	@Override
	public void create() {
		addImageLayer("images/opening_act.png");
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see com.jfbuilds.playngame.scenes.JFBSceneInterface#getSceneAbilities()
	 */
	@Override
	public ArrayList<JFBSceneAbilityInterface> getSceneAbilities() {
		// TODO Auto-generated method stub
		return null;
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see com.jfbuilds.playngame.scenes.JFBSceneInterface#getSceneFragments()
	 */
	@Override
	public ArrayList<JFBFragmentInterface> getSceneFragments() {
		// TODO Auto-generated method stub
		return null;
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see com.jfbuilds.playngame.scenes.JFBSceneInterface#getSceneObjectives()
	 */
	@Override
	public ArrayList<JFBSceneObjectiveInterface> getSceneObjectives() {
		// TODO Auto-generated method stub
		return null;
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see com.jfbuilds.playngame.scenes.JFBSceneInterface#getTransition()
	 */
	@Override
	public JFBTransitionInterface getTransition() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void init() {
		initBase();
		create();

		// GroupLayer base = graphics().createGroupLayer();
		// Image image = assets().getImage("images/act_1.png");
		// ImageLayer imageLayer = graphics().createImageLayer(image);
		// base.add(imageLayer);
		// setBase(base);
	}

	@Override
	public void initBase() {
		GroupLayer base = graphics().createGroupLayer();
		setBase(base);
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see
	 * com.jfbuilds.playngame.scenes.JFBSceneInterface#setSceneAbilities(java
	 * .util.ArrayList)
	 */
	@Override
	public void setSceneAbilities(ArrayList<JFBSceneAbilityInterface> sceneAbilities_) {
		// TODO Auto-generated method stub

	}

	/*
	 * (non-Javadoc)
	 *
	 * @see
	 * com.jfbuilds.playngame.scenes.JFBSceneInterface#setSceneFragments(java
	 * .util.ArrayList)
	 */
	@Override
	public void setSceneFragments(ArrayList<JFBFragmentInterface> sceneFragments_) {
		// TODO Auto-generated method stub

	}

	/*
	 * (non-Javadoc)
	 *
	 * @see
	 * com.jfbuilds.playngame.scenes.JFBSceneInterface#setSceneObjectives(java
	 * .util.ArrayList)
	 */
	@Override
	public void setSceneObjectives(ArrayList<JFBSceneObjectiveInterface> sceneObjectives_) {
		// TODO Auto-generated method stub

	}

	/*
	 * (non-Javadoc)
	 *
	 * @see
	 * com.jfbuilds.playngame.scenes.JFBSceneInterface#setTransition(com.jfbuilds
	 * .playngame.general.JFBTransitionInterface)
	 */
	@Override
	public void setTransition(JFBTransitionInterface transition_) {
		// TODO Auto-generated method stub

	}

}