/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

import java.util.ArrayList;

import com.jfbuilds.playngame.abilities.JFBSceneAbilityInterface;
import com.jfbuilds.playngame.fragments.JFBFragmentInterface;
import com.jfbuilds.playngame.general.JFBContainerInterface;
import com.jfbuilds.playngame.general.JFBTransitionInterface;
import com.jfbuilds.playngame.objectives.JFBSceneObjectiveInterface;

/**
 *
 **/
public interface JFBSceneInterface extends JFBContainerInterface {

	/* ===================================== */
	/* == Member Variables == */
	/* ===================================== */

	// private ArrayList<JFBSceneObjectiveInterface> sceneObjectives;
	//
	// private ArrayList<JFBSceneAbilityInterface> sceneAbilities;
	//
	// private ArrayList<JFBFragmentInterface> sceneFragments;
	//
	// private JFBTransitionInterface transition;

	/* ===================================== */
	/* == Methods == */
	/* ===================================== */

	/**
	 *
	 **/
	public ArrayList<JFBSceneAbilityInterface> getSceneAbilities();

	/**
	 *
	 **/
	public ArrayList<JFBFragmentInterface> getSceneFragments();

	/**
	 *
	 **/
	public ArrayList<JFBSceneObjectiveInterface> getSceneObjectives();

	/**
	 *
	 **/
	public JFBTransitionInterface getTransition();

	/**
	 *
	 **/
	public void setSceneAbilities(ArrayList<JFBSceneAbilityInterface> sceneAbilities_);

	/**
	 *
	 **/
	public void setSceneFragments(ArrayList<JFBFragmentInterface> sceneFragments_);

	/**
	 *
	 **/
	public void setSceneObjectives(ArrayList<JFBSceneObjectiveInterface> sceneObjectives_);

	/**
	 *
	 **/
	public void setTransition(JFBTransitionInterface transition_);

}