/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

import com.jfbuilds.playngame.general.JFBContainerInterface;

/**
 *
 **/
public class MindPuzzleStage extends SimpleStageScene implements JFBSceneInterface {

	public MindPuzzleStage(String name_, JFBContainerInterface parent_) {
		super(name_, parent_);
	}

}