/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

/**
 *
 **/
public class MindPuzzleStage extends SimpleStageScene implements JFBSceneInterface {

	public MindPuzzleStage(String name_) {
		super(name_);
		// TODO Auto-generated constructor stub
	}

}