/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

import com.jfbuilds.playngame.general.JFBContainerInterface;

/**
 *
 **/
public class SimpleMovieScene extends SimpleScene implements JFBSceneInterface {

	public SimpleMovieScene(String name_, JFBContainerInterface parent_) {
		super(name_, parent_);
	}

}