/* Generated by Quick UML for Java */

package com.jfbuilds.playngame.scenes;

/**
 *
 **/
public class SimpleMovieScene extends SimpleScene implements JFBSceneInterface {

	public SimpleMovieScene(String name_) {
		super(name_);
		// TODO Auto-generated constructor stub
	}

}